// Generated by CoffeeScript 1.4.0
(function() {

  Array.prototype.any = function(func) {
    var ele;
    return ((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        ele = this[_i];
        if (func(ele)) {
          _results.push(1);
        }
      }
      return _results;
    }).call(this)).length > 0;
  };

}).call(this);
