// Generated by CoffeeScript 1.4.0
(function() {
  var FixSizeAnimiationFactory;

  FixSizeAnimiationFactory = (function() {

    function FixSizeAnimiationFactory(imageName, frameWidth, frameHeight) {
      this.imageName = imageName;
      this.frameWidth = frameWidth;
      this.frameHeight = frameHeight;
    }

    FixSizeAnimiationFactory.prototype.createWithFrames = function(frames) {
      return new Animation(this.imageName, frames, this.frameWidth, this.frameHeight);
    };

    return FixSizeAnimiationFactory;

  })();

  window.FixSizeAnimiationFactory = FixSizeAnimiationFactory;

}).call(this);
