// Generated by CoffeeScript 1.4.0
(function() {
  var Game;

  Game = (function() {

    function Game(hero, context) {
      this.hero = hero;
      this.context = context;
      this.objects = [this.hero];
      this.polices = [];
    }

    Game.prototype.addObject = function(object) {
      return this.objects.push(object);
    };

    Game.prototype.addPolice = function(police) {
      this.polices.push(police);
      return this.addObject(police);
    };

    Game.prototype.checkCollision = function() {
      var theHero;
      theHero = this.hero;
      return this.polices.any(function(police) {
        return police.overlapWith(theHero);
      });
    };

    Game.prototype.render = function() {
      var object, _i, _len, _ref, _results;
      this.context.clearRect(0, 0, GlobalConfig.width, GlobalConfig.height);
      _ref = this.objects;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        object = _ref[_i];
        _results.push(object.draw(this.context, 30));
      }
      return _results;
    };

    Game.prototype.failScreen = function() {
      var alpha, delta, fadeOut, self;
      alpha = 100;
      delta = 5;
      self = this;
      fadeOut = function() {
        alpha -= delta;
        self.context.globalAlpha = alpha / 100;
        self.render();
        if (alpha > 0) {
          return setTimeout(fadeOut, 50);
        } else {
          self.context.globalAlpha = 1;
          self.context.font = 'italic 40pt Calibri';
          self.context.drawImage(ImageManager.getImageByName("fail"), 0, 0, 350, 300);
          return self.context.fillText("You are arrested!!!!", 400, 150);
        }
      };
      return setTimeout(fadeOut, 50);
    };

    Game.prototype.checkWin = function() {
      return this.hero.x + Hero.width + 10 > GlobalConfig.width;
    };

    Game.prototype.winScreen = function() {
      this.context.drawImage(ImageManager.getImageByName("win"), 1300, 0, 1350, 666, 0, 0, GlobalConfig.width, GlobalConfig.height);
      this.context.font = 'italic 40pt Calibri';
      this.context.fillStyle = 'red';
      this.context.fillText("You reach the destination!!!!", 200, 150);
      return this.context.fillText("Congratulations!!!!", 300, 250);
    };

    Game.prototype.start = function() {
      var self;
      this.render();
      if (this.checkCollision()) {
        return this.failScreen();
      } else if (this.checkWin()) {
        return this.winScreen();
      } else {
        self = this;
        return setTimeout(function() {
          return self.start();
        }, 30);
      }
    };

    return Game;

  })();

  window.Game = Game;

}).call(this);
