// Generated by CoffeeScript 1.4.0
(function() {
  var GlobalConfig;

  GlobalConfig = (function() {

    function GlobalConfig() {}

    GlobalConfig.width = 1024;

    GlobalConfig.height = 300;

    GlobalConfig.collisionTolerant = 20;

    return GlobalConfig;

  })();

  window.GlobalConfig = GlobalConfig;

}).call(this);
