// Generated by CoffeeScript 1.4.0
(function() {
  var frameHeigth, frameWidth, frames;

  frameWidth = 64;

  frameHeigth = 100;

  frames = function(y) {
    var index, _i, _len, _ref, _results;
    _ref = [0, 1, 2, 3];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      index = _ref[_i];
      _results.push({
        left: index * frameWidth,
        top: y,
        duration: 200
      });
    }
    return _results;
  };

  window.upFrames = function() {
    return frames(300);
  };

  window.leftFrames = function() {
    return frames(100);
  };

  window.rightFrames = function() {
    return frames(200);
  };

  window.downFrames = function() {
    return frames(0);
  };

}).call(this);
