// Generated by CoffeeScript 1.4.0
(function() {
  var Police;

  Police = (function() {

    Police.img = "image/jingcha.jpg";

    Police.width = 60;

    Police.height = 100;

    function Police(x, y, speed) {
      this.x = x;
      this.y = y;
      this.speed = speed;
      this.state = new UpState();
      this.image = ImageManager.getImageByName("police");
    }

    Police.prototype.udpateState = function(state) {
      return this.state = state;
    };

    Police.prototype.withinBoundary = function(newPosition) {
      var x, y;
      x = newPosition.x;
      y = newPosition.y;
      return x > 0 && x < GlobalConfig.width - Police.width && y > 0 && y < GlobalConfig.height - Police.height;
    };

    Police.prototype.overlapWith = function(hero) {
      var tolerant;
      tolerant = GlobalConfig.collisionTolerant;
      return !(this.x + tolerant > Hero.width + hero.x || this.x + Police.width < hero.x + tolerant || this.y + tolerant > Hero.height + hero.y || this.y + Police.height < hero.y + tolerant);
    };

    Police.prototype.draw = function(context, delta) {
      var newPosition;
      newPosition = this.state.getNextPosition(this.x, this.y, this.speed * delta / 1000);
      if (this.withinBoundary(newPosition)) {
        this.x = newPosition.x;
        this.y = newPosition.y;
      } else {
        this.state = this.state.opposite();
      }
      return context.drawImage(this.image, this.x, this.y, Police.width, Police.height);
    };

    return Police;

  })();

  window.Police = Police;

}).call(this);
