// Generated by CoffeeScript 1.4.0
(function() {
  var DownState, LeftState, RightState, UpState;

  LeftState = (function() {

    function LeftState() {}

    LeftState.prototype.getNextPosition = function(x, y, distance) {
      return {
        x: x - distance,
        y: y
      };
    };

    LeftState.prototype.opposite = function() {
      return new RightState();
    };

    return LeftState;

  })();

  UpState = (function() {

    function UpState() {}

    UpState.prototype.getNextPosition = function(x, y, distance) {
      return {
        x: x,
        y: y - distance
      };
    };

    UpState.prototype.opposite = function() {
      return new DownState();
    };

    return UpState;

  })();

  RightState = (function() {

    function RightState() {}

    RightState.prototype.getNextPosition = function(x, y, distance) {
      return {
        x: x + distance,
        y: y
      };
    };

    RightState.prototype.opposite = function() {
      return new LeftState();
    };

    return RightState;

  })();

  DownState = (function() {

    function DownState() {}

    DownState.prototype.getNextPosition = function(x, y, distance) {
      return {
        x: x,
        y: y + distance
      };
    };

    DownState.prototype.opposite = function() {
      return new UpState();
    };

    return DownState;

  })();

  window.LeftState = LeftState;

  window.UpState = UpState;

  window.RightState = RightState;

  window.DownState = DownState;

}).call(this);
